### ISSUE TITLE
Move to official github pages deployment action

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#49]
Apparently there an official GH Pages action developed by the GitHub team!
https://github.com/actions/deploy-pages

This circumvents issues with the `JamesIves/github-pages-deploy-action` action i was using before, and ensure it will be maintained in the long-term:
https://github.com/JamesIves/github-pages-deploy-action/issues/1310

**Comment by bschilder** [comment]
Got most of the way through, but ran into permissions issues:

```
/usr/bin/docker exec  48e8427ea2118d473bfd5f938bc83fd32abdabb7eab3d919050fbefaf090e3bd sh -c "cat /etc/*release | grep ^ID"
Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
    at Function.<anonymous> (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:71:1)
    at Generator.next (<anonymous>)
    at /__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:8:1
    at new Promise (<anonymous>)
    at __webpack_modules__.8041.__awaiter (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:4:1)
    at Function.getIDToken (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:57:1)
    at Object.<anonymous> (/__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/core.js:315:1)
    at Generator.next (<anonymous>)
    at /__w/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/core.js:27:1
    at new Promise (<anonymous>)
Error: Ensure GITHUB_TOKEN has permission "id-token: write".
```
Try using the `permissions` section in the yaml:
https://github.com/actions/deploy-pages

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by bschilder** [comment]
The action didn't seem to like this. Perhaps needs to go in a different part of the yaml:

```
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'neurogenomics/rworkflows@master' (SHA:51ac93d215d204790ba2e5f1b5c0b6ee3e00c47e)
Error: neurogenomics/rworkflows/master/action.yml (Line: 84, Col: 3): Unexpected value 'permissions'
Error: neurogenomics/rworkflows/master/action.yml (Line: 84, Col: 3): Unexpected value 'permissions'
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. neurogenomics/rworkflows/master/action.yml (Line: 84, Col: 3): Unexpected value 'permissions'
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```

**Comment by bschilder** [comment]
Helpful blog:
https://dev.to/azu/how-to-set-github-actions-s-permissions-hln

**Comment by bschilder** [comment]
Created a dev branch to work on this without break the master branch.
 Made a new workflow file called *rworkflows_dev.yml*

**Comment by bschilder** [comment]
There's currently several drawbacks to the `action/deploy-pages` action:

> This action expects an artifact named github-pages to have been created prior to execution. This is done automatically when using [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact).

This adds extra steps, making `rworkflows` action less clean and more complicated.

> We recommend this action to be used in a dedicated job

This isn't compatible with how `rworkflows` tries to integrate all steps into one action.


For now, will continue using `JamesIves/github-pages-deploy-action`, which is currently used even more than the `action/deploy-pages` action (335k vs. 306k) and has Sponsorship from key developers like Hadley Wickham (Posit). Will reopen this Issue if the landscape shifts later on.
